//@version=5
// Author: Akash Sasikumar
// Copyright: 2023.Akash sasikumar
indicator(title="Stochastic Oscillator", shorttitle="Stoch", overlay=false)

length = input.int(14, title="Stoch Length")
k_smooth = input.int(3, title="%K Smoothing")
d_smooth = input.int(3, title="%D Smoothing")

source_high = input(high, title="High Source")
source_low = input(low, title="Low Source")
source_close = input(close, title="Close Source")

higest_high = ta.highest(source_high, length)
lowest_low = ta.lowest(source_low, length)

stoch_k = 100 * (source_close - lowest_low) / (higest_high - lowest_low)
stoch_k_smoothed = ta.sma(stoch_k, k_smooth)
stoch_d = ta.sma(stoch_k_smoothed, d_smooth)

plot(stoch_k_smoothed, title="%K", color=color.blue)
plot(stoch_d, title="%D", color=color.red)

hline(80, title="Overbought", color=color.red)
hline(20, title="Oversold", color=color.green)